"""
     1.define a class queue to implement queue data structure using list .define __init__() method to create an empty list object as instance object member of queue
     2.DEFINE A METHOOD IS EMPTY () TO CHECK IF THE QUEUE IS EMPTY IN QUEUE C LASS
     3.IN QUEUE CLASS DEFINE ENQUEUE() METHOD TO ADD THE DATA AT THE REAR END OF THE QUEUE
     4.IN QUEUE CLASS DEFINE DEQUEUE() METHOD TO REMOVE FRONT ELEMENT FROM QUEUE
     5.IN QUEUE CLASS DEFINE GET_FRONT() METHOD TO RETURN FRONT ELEMENT OF THE QUEUE
     6.IN QUEUE CLASS,DEFINE GET_REAR() METHOD TO RETURN REAR ELEMMENT OF THE QUEUE
     7.IN QUEUE CLASS DEFINE SIZE() METHOD TO RETURN SIZE OF TH QUEUE THAT IS NUMBER OF ITEMS PRESENT IN THE QUEUE.


"""

class Queue(list):
    
